resilience4j.rate-limiter:
  configs:
    default:
      limitForPeriod: 10
      limitRefreshPeriod: 5s
      timeoutDuration: 20s
      registerHealthIndicator: true
      eventConsumerBufferSize: 100
  instances:
    weatherAPILimiter:
      baseConfig: default
    calendarAPILimiter:
      baseConfig: default
      limitForPeriod: 10